version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "infra"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "org.apache.nifi:*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directories:
      - "/extensions/*/*/nifi-*-bundle"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "extensions"
    ignore:
      - dependency-name: "org.apache.nifi:*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/flows"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "flows"
